services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsOpenSearchBundle\Command\RebuildIndexCommand:
        tags:
            - { name: console.command}
