services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsOpenSearchBundle\Command\RebuildIndexCommand:
        arguments:
            $dsFullConfiguration: '%dynamic_search.context.full_configuration%'
        tags:
            - { name: console.command}