services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Output Channel Services

    DsOpenSearchBundle\OutputChannel\SearchOutputChannel:
        tags:
            - { name: dynamic_search.output_channel, identifier: opensearch_search }

    # Filter / Action

    DsOpenSearchBundle\OutputChannel\Modifier\Filter\QueryCleanTermFilter:
        tags:
            - { name: dynamic_search.output_channel.modifier.filter, output_channel_service_identifier: opensearch_search, filter: query.clean_term }
